
#General settings
[general]
	#Use config instead of datapack
	use_config = true

	#List settings
	#Syntax: ["modid:block|weight"]
	#Example: ["minecraft:stone|2","minecraft:dirt|1"]
	#Forge tags are supported
	[general.lists]
		#Cobble gen
		block_list_basalt = ["minecraft:basalt|1", "minecraft:basalt|1"]
		#Cobble gen
		block_list_cobble = ["minecraft:cobblestone|1", "minecraft:cobblestone|1"]
		#Stone gen
		block_list_stone = ["minecraft:stone|1", "minecraft:stone|1"]

		#Custom settings
		[general.lists.custom]
			#Custom generators
			#Syntax: [gen]
			#Gen: [type, block, list]
			#Type: cobblestone, stone
			#Block: resource location of the block below the generated block
			#List: see List settings
			#Examples:
			#custom_generators = [
			#   ["cobblestone", "minecraft:diamond_block", ["minecraft:diamond_block"]],
			#   ["cobblestone", "minecraft:dirt", ["forge:dirt"]],
			#   ["cobblestone", "minecraft:white_wool", ["minecraft:wool"]]]
			custom_generators = [
				 ["cobblestone", "minecraft:iron_block", ["chroma:cobbleworks/cobblestone"]],
		  	 ["cobblestone", "undergarden:tremblecrust", ["undergarden:tremblecrust"]],
				 ["cobblestone", "undergarden:depthrock", ["undergarden:depthrock"]],
				 ["cobblestone", "undergarden:shiverstone", ["undergarden:shiverstone"]],
				 ["cobblestone", "minecraft:blackstone", ["minecraft:blackstone"]],
				 ["cobblestone", "minecraft:cobbled_deepslate", ["minecraft:cobbled_deepslate"]],
				 ["stone", "minecraft:diamond_block", ["chroma:cobbleworks/stone"]],
				 ["stone", "minecraft:andesite", ["minecraft:andesite"]],
				 ["stone", "minecraft:diorite", ["minecraft:diorite"]],
				 ["stone", "minecraft:granite", ["minecraft:granite"]],
				 ["stone", "minecraft:calcite", ["minecraft:calcite"]],
				 ["stone", "minecraft:red_sandstone", ["minecraft:red_sandstone"]],
				 ["stone", "minecraft:sandstone", ["minecraft:sandstone"]],
				 ["stone", "quark:jasper", ["quark:jasper"]],
				 ["stone", "quark:limestone", ["quark:limestone"]],
				 ["stone", "quark:permafrost", ["quark:permafrost"]],
				 ["stone", "create:crimsite", ["create:crimsite"]],
				 ["stone", "create:limestone", ["create:limestone"]],
				 ["stone", "create:ochrum", ["create:ochrum"]],
				 ["stone", "create:scorchia", ["create:scorchia"]],
				 ["stone", "create:scoria", ["create:scoria"]],
				 ["stone", "create:asurine", ["create:asurine"]],
				 ["stone", "create:veridium", ["create:veridium"]]
		 ]
